=== Muhlex/vscode-gsc/schemas/CallableDefGame.json
{
  "$ref": "#/definitions/CallableDefGame",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "CallableDefGame": {
      "additionalProperties": false,
      "properties": {
        "deprecated": {
          "type": "boolean"
        },
        "description": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "devOnly": {
          "type": "boolean"
        },
        "example": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "params": {
          "items": {
            "$ref": "#/definitions/ParamDef"
          },
          "type": "array"
        },
        "paramsRepeatable": {
          "enum": [
            "last",
            "all"
          ],
          "type": "string"
        },
        "priority": {
          "type": "number"
        },
        "receiver": {
          "$ref": "#/definitions/VariableDef"
        },
        "return": {
          "additionalProperties": false,
          "properties": {
            "description": {
              "items": {
                "type": "string"
              },
              "type": "array"
            },
            "name": {
              "type": "string"
            },
            "types": {
              "items": {
                "type": "string"
              },
              "type": "array"
            }
          },
          "type": "object"
        }
      },
      "type": "object"
    },
    "ParamDef": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        },
        "optional": {
          "type": "boolean"
        },
        "types": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    },
    "VariableDef": {
      "additionalProperties": false,
      "properties": {
        "description": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "name": {
          "type": "string"
        },
        "optional": {
          "type": "boolean"
        },
        "types": {
          "items": {
            "type": "string"
          },
          "type": "array"
        }
      },
      "type": "object"
    }
  }
}

=== Muhlex/vscode-gsc/src/build/defs/iw4/callable/common/HUD/iPrintLn.json
{
	"description": ["Write a line of text to the bottom left output (shared with e. g. obituaries)."],
	"params": [
		{
			"name": "text",
			"types": ["string", "int", "float", "vector"]
		}
	],
	"paramsRepeatable": "last",
	"receiver": {
		"types": ["world", "player"],
		"description": ["If called on a player, only they will see the line."]
	}
}

=== Muhlex/vscode-gsc/src/build/defs/iw4/callable/iw4x/IO/openFile.json
{
	"priority": 1,
	"description": [
		"Open a file for reading. The file is implicitly stored in global state, thus only one file can be open at a time. Close with `closeFile`."
	],
	"params": [
		{
			"name": "path",
			"types": ["string"],
			"description": ["Path to the file."]
		},
		{
			"name": "mode",
			"types": ["\"read\""],
			"description": ["Mode to open the file in. Must be `\"read\"`."]
		}
	],
	"return": {
		"name": "success",
		"types": ["int"],
		"description": ["`1` on success, `-1` if the file could not be opened."]
	}
}

=== Muhlex/vscode-gsc/src/build/defs/iw4/callable/common/DVar/setClientDvar.json
{
	"description": ["Set the value of a DVar locally for a player."],
	"params": [
		{
			"name": "dvar",
			"types": ["string"],
			"description": ["Name of the DVar."]
		},
		{
			"name": "value",
			"types": ["string", "int", "float", "vector"],
			"description": ["Value to set."]
		}
	],
	"receiver": {
		"types": ["player"],
		"description": ["The player on which to set the DVar."]
	},
	"example": ["self setClientDvar(\"cg_drawGun\", 0)"]
}
